version: "{build}"

image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1

cache:
- packages -> **\packages.config

install:
- ps: >-
    $env:BUILD_VERSION = Select-String -Path Server\Properties\AssemblyInfo.cs -Pattern 'AssemblyFileVersion\(\"(.*)\"\)' | %{ $_.Matches[0].Groups[1].Value }

    If ($env:APPVEYOR_REPO_TAG -eq $true) {
      $env:BUILD_VERSION = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")
    }

    $env:BUILD_VERSION_FILE = "$env:BUILD_VERSION.$env:APPVEYOR_BUILD_NUMBER"

    Update-AppveyorBuild -Version $env:BUILD_VERSION_FILE

    $version = $env:BUILD_VERSION -split '-'

    $env:BUILD_VERSION_FRIENDLY = $version[0] -replace "(\.0)$"

    If ($version[1]) {
      $env:BUILD_VERSION_FILE = "$($version[0]).$env:APPVEYOR_BUILD_NUMBER"

      Update-AppveyorBuild -Version "$env:BUILD_VERSION_FILE-$($version[1])"

      $end = (Get-Culture).TextInfo.ToTitleCase($version[1].Replace("rc", "RC"))
      $env:BUILD_VERSION_FRIENDLY += " " + $end -replace "([a-z]+)(\d+)",'$1 $2'
    }

    $env:BUILD_VERSION_FRIENDLY += " Build $env:APPVEYOR_BUILD_NUMBER"

assembly_info:
  patch: true
  file: '**\Properties\AssemblyInfo.cs'
  assembly_version: $(BUILD_VERSION)
  assembly_file_version: $(BUILD_VERSION_FILE)
  assembly_informational_version: $(BUILD_VERSION_FRIENDLY)

before_build:
- nuget restore

build:
  project: NFive.sln
  verbosity: minimal

after_build:
- 7z a dark5.zip README.md LICENSE *.dll dark5.yml dark5.lock fxmanifest.lua index.html config\

artifacts:
- path: dark5.zip

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: vHSyTGwtKB1CVyhDA5DUSpDnrBX6j9cjj46e1CUspjBEeKTRdSDewfRwq/1X0XNo
  on:
    APPVEYOR_REPO_TAG: true
