-- FX resource definition
-- This file is automatically generated with `nfpm install` - any manual changes will be lost

fx_version 'cerulean'
game 'gta5'

server_scripts {
	-- Dark5
	'Dark5.Server.net.dll',
}

client_scripts {
	-- Dark5
	'Dark5.Client.net.dll',
}

files {
	-- Dark5
	'DotNetZip.dll',
	'Newtonsoft.Json.dll',
	'NGettext.dll',
	'System.ComponentModel.DataAnnotations.dll',
	'Dark5.SDK.Core.net.dll',
	'Dark5.SDK.Client.net.dll',
	'index.html',
}

-- NFive
ui_page 'index.html'
